### ISSUE TITLE
Please remove the last `/`

### ISSUE THREAD

**Issue by blackcodersec** [sanjai-AK47/SubProber#1]
Your script is good, can you remove the `/` from the url? And I found that if I don't input `-o` command still the output file saves a `subprober_results.txt`. I think it should not be right. you can check other script.

![image](https://github.com/sanjai-AK47/SubProber/assets/72689232/125d58b9-eab3-45fd-a8ac-ce67d1538850)

**Comment by sanjai-AK47** [comment]
@blackcodersec Thanks for reporting your issues but here I want to explain that to saving automatic is default because some users need to save results to automatically without giving any `-o` , so for that I have made the script but after this I will also make some changes in next version that you make subprober to not save results by defaul by adding one more flag and Here I want to explain one more thing is `/` in url is coming because subprober have one more functionality to use with `-p` to fuzz path ex: `-p log.txt` so when user doesnt give any `-p` option, the results will come with ending slash for output alignment , as these are some functionalities of subprober if you want to make anyother changes means please you can report here .

**Comment by blackcodersec** [comment]
thanks for your reply. but I saw most of the people are now use multiple script with pipe `|`, so when I use a script then I can't run your script with pipe, because of auto save output file. another think is `/`, I think researcher are use `ffuf` and `dirsearch` for the fuzzing. as your wish.
btw, I hope you push new code ASAP.

thanks

**Comment by sanjai-AK47** [comment]
Ah I can Understand your problem now , you can't connect to subprober ouput to other tools via `|` because the outputs are colorised and that's why you can't pipe it even httpx also but for that I recommend my another tools for you so you can pipe it that output , you can install that tool by this command:
 ```bash 
pip install httprober
```
This tool output supports both stdin/stdout

**Comment by blackcodersec** [comment]
Hi there,
I saw your `httprober` script. this script also same doing that like auto output file generated. and less function than `SubProber`.
`SubProber` is good script. could you change it please.

**Comment by sanjai-AK47** [comment]
Hey after reviewing your issue I have resolved it and you can check out the update in  `v1.0.6`
